apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suitecrm.fullname" . }}
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "suitecrm.labels" . | nindent 8 }}
        component: app
        route-ingress: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: SUITECRM_URL
              value: https://{{.Values.global.suitecrmHost}}
            - name: ServerName
              value: {{.Values.global.suitecrmHost}}
            - name: APP_SECRET
              value: {{ randAlphaNum 32 | quote }}
            - name: SUITE_DB_HOST
              value: suitecrm-mariadb-galera
            - name: SUITE_DB_USER
              value: {{ index (index (index .Values "mariadb-galera") "db") "user" }}
            - name: SUITE_DB_PASSW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.databaseSecretName}}
                  key: mariadb-password
            - name: SUITE_DB_NAME
              value: {{ index (index (index .Values "mariadb-galera") "db") "name" }}
            - name: SUITE_DB_PORT
              value: '3306'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.suitecrmSecretName }}
                  key: database-url
            - name: SUITECRM_ADMIN_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.suitecrmSecretName }}
                  key: suitecrm-admin-password
            - name: OPCACHE_ENABLE
              value: '1'
            - name: AUTH_TYPE
              value: saml
            - name: SAML_USERNAME_ATTRIBUTE
              value: idir_username
            - name: SAML_USE_ATTRIBUTE_FRIENDLY_NAME
              value: 'false'
            - name: SAML_IDP_ENTITY_ID
              value: https://{{.Values.global.ssoDomain}}/auth/realms/{{.Values.global.ssoRealm}}
            - name: SAML_IDP_X509CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.suitecrmSecretName }}
                  key: sso-idp-x509
            - name: SAML_IDP_SSO_URL
              value: >-
                https://{{.Values.global.ssoDomain}}/auth/realms/{{.Values.global.ssoRealm}}/protocol/saml
            - name: SAML_IDP_SLO_URL
              value: >-
                https://{{.Values.global.ssoDomain}}/auth/realms/{{.Values.global.ssoRealm}}/protocol/saml
            - name: SAML_SP_ENTITY_ID
              value: {{.Values.global.ssoClientid}}
            - name: SAML_SP_CERT
              valueFrom:
                secretKeyRef:
                  name: suitecrm-secrets
                  key: sso-idp-x509
            - name: SAML_DEBUG
              value: 'true'
            - name: REDIS_LOCKING
              value: '1'
            - name: SAML_COMPRESS_REQUESTS
              value: 'true'
            - name: SAML_COMPRESS_RESPONSES
              value: 'true'
            - name: SAML_STRICT
              value: 'true'
            - name: SAML_NAME_ID_ENCRYPTED
              value: 'true'
            - name: SAML_SIGN_METADATA
              value: 'true'
            - name: SAML_WANT_NAME_ID
              value: 'true'
            - name: SAML_WANT_ASSERTIONS_SIGNED
              value: 'true'
            - name: SAML_REQUESTED_AUTHN_CONTEXT
              value: 'true'
            - name: SAML_WANT_XML_VALIDATION
              value: 'true'
            - name: SAML_WANT_MESSAGES_SIGNED
              value: 'true'
            - name: SESSION_SAVE_HANDLER
              value: rediscluster
            - name: SESSION_SAVE_PATH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.suitecrmSecretName }}
                  key: redis-path
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /auth
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /auth
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts: 
            - name: {{ .Values.global.volume.name }}
              mountPath: /suitecrm/public/legacy/upload
      volumes:
        - name: {{ .Values.global.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.volume.claimName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}