framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  #http_method_override: true
  annotations: false
  http_method_override: false
  handle_all_throwables: true

  # Note: Session will only be started if you read or write from it.
  session:
    cookie_lifetime: null
    cookie_secure: auto
    cookie_samesite: lax
#    storage_factory_id: session.storage.factory.legacy_bridge
#    handler_id: session.handler.legacy_bridge
#    save_path: ~
    handler_id: '%env(SESSION_SAVE_HANDLER_ID)%'
    save_path: '%env(SESSION_SAVE_PATH)%'

  php_errors:
    log: true

  assets:
      base_path: '/'