name: SuiteCRM Build and Update

on:
  push:
    branches:
      - update_docker
  workflow_dispatch: # Add the workflow_dispatch trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set SuiteCRM URL
        run: echo "::set-env name=SUITECRM_URL::${{ secrets.SUITECRM_URL }}"

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: suitecrm:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Add deployment steps here if needed
